version: '3.1'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: origin
      POSTGRES_DB: db
    volumes:
      - ./my-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'